apiVersion: v1
kind: Service
metadata:
  name: {{ template "jaeger.fullname" . }}-agent
  labels:
    app: {{ template "jaeger.name" . }}
    chart: {{ template "jaeger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: jaeger
spec:
  type: {{ .Values.service.agent.type }}
  selector:
    app: {{ template "jaeger.name" . }}
    release: {{ .Release.Name }}
    component: jaeger
  ports:
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
