{
 "title": "Pushync - PSS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "view_by",
    "label": "View by",
    "query": "$tag_host:$tag_bzzkey, $tag_host:$tag_pubkey, $tag_host, $tag_bzzkey,$tag_pubkey"
   },
   { "name": "myinterval", "label": "resolution", "query": "5s,10s,30s,100s" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "bzzkey",
    "query": "SHOW TAG VALUES WITH KEY = \"bzzkey\""
   },
   {
    "name": "pubkey",
    "query": "SHOW TAG VALUES WITH KEY = \"pubkey\""
   }
  ]
 },
 "panels": [
  {
   "title": "Pss - Handle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "handle [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.handle.span",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss - Process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "process [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.process.span",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss - Enqueue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "enqueue [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.enqueue.span",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss - Forward",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "forward [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.forward.time.span",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss - Pubsub Send",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.pubsub.send.span",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss - PP Send",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.pp.send.span",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Outbox len",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "Len" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.outbox.len.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Outbox workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "Len" }
   ],
   "targets": [
    {
     "alias": "workers [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.outbox.workers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS. pubsub send time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "%95 [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.pubsub.send.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.pubsub.send.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS. Forward time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "%95 [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.forward.time.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.forward.time.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS. handle outbox time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "%95 [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.handle.outbox.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.handle.outbox.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "PSS. Peer send_t",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "%95 [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send_t.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.peer.send_t.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss - FwdCache Hits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Hits [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.checkfwdcache.hit.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss - FwdCache Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Misses [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.checkfwdcache.miss.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Storer - Put time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "mean [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.localstore.Put.Sync.total-time.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "95% [[view_by]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.localstore.Put.Sync.total-time.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss -Retries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.outbox.retries.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss -Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "errors [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.forward.err.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "errors [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.pp.send.error.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pss - Expired",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.forward.expired.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pss.expire.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "Receipts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Mark and sweep - timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.mark-and-sweep.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Receipts - not found",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.receipts.not-found.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Receipts - all",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.receipts.all.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Receipts - already synced",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.receipts.already-synced.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Receipts - synced",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.receipts.synced.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "All measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Pusher send chunk - all",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.send-chunk.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Pusher send chunk - send to sync",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.send-chunk.send-to-sync.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Push Sync - chunk roundtrip - timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "95% - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.chunk.roundtrip.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.chunk.roundtrip.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "50% - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.chunk.roundtrip.span",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Push Sync - send chunk - PSS timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "95% - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.send.chunk.pss.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.send.chunk.pss.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Push Sync - chunk roundtrip - count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "sum(count) - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.chunk.roundtrip.span",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Push Sync - send chunk - RLP ser timer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "95% - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.send.chunk.rlp.span",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "mean - [[view_by]]",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bzzkey" ], "type": "tag" },
      { "params": [ "pubkey" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swarm.pusher.send.chunk.rlp.span",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "bzzkey", "operator": "=~", "value": "/^$bzzkey$/" },
      { "condition": "AND", "key": "pubkey", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  }
 ]
}